// <auto-generated />
using System;
using Maersk.SCM.DeliveryPlanning.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Maersk.SCM.DeliveryPlanning.Infrastructure.Migrations
{
    [DbContext(typeof(DeliveryPlanningDbContext))]
    partial class DeliveryPlanningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Maersk.SCM.DeliveryPlanning.Domain.Aggregates.DeliveryOrderAggregate.DeliveryOrderReference", b =>
                {
                    b.Property<Guid>("DeliveryOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DeliveryOrderNumberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("DeliveryOrderId");

                    b.ToTable("DeliveryOrderReferences");
                });

            modelBuilder.Entity("Maersk.SCM.DeliveryPlanning.Domain.Events.DeliveryOrderDomainEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "Version");

                    b.ToTable("DeliveryOrderEvents");
                });

            modelBuilder.Entity("Maersk.SCM.DeliveryPlanning.Domain.Events.DeliveryPlanDomainEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "Version");

                    b.ToTable("DeliveryPlanEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
